development:
  adapter: postgresql
  encoding: utf8
  database: demonet_development
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  adapter: postgresql
  database: demonet_development
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
